### ISSUE TITLE
Marker not set when file skipped

### ISSUE THREAD

**Issue by LewisW** [sourcey/s3-image-optimizer#1]
The marker isn't set when an image is skipped. What's the reason for this? The reason I ask is: I think we've got the scenario where `listKeyPage` returns an entire set of keys that are all skipped - but because the marker is never updated on skip, it just keeps retrying the same page over an over again.

Are their any negative side-affects of still setting the marker when a file is skipped?

**Comment by emersonbroga** [comment]
I think it makes sense to add the skipped ones to the marker file.

PR Created: https://github.com/sourcey/s3-image-optimizer/pull/9

**Comment by auscaster** [comment]
Fixed via PR
