### ISSUE TITLE
Deployment is failing as the current version of nodejs has been deprecated by AWS

### ISSUE THREAD

**Issue by shashankkr9** [sourcey/s3-image-optimizer#8]
Error:

`[InvalidParameterValueException: The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs4.3) while creating or updating functions.]
  message: 'The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs4.3) while creating or updating functions.',
  code: 'InvalidParameterValueException'`

**Comment by auscaster** [comment]
Fixed on 2147bd66805904b3c3d714b6c2c574681dbbdc21
